version: "3.9"
services:
  dnsmasq:
    image: quay.io/poseidon/dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: >
      -d -q
      --dhcp-range=10.179.1.50,10.179.3.255
      --dhcp-host=A0:63:91:E7:C0:88,10.179.1.1,1h
      --enable-tftp --tftp-root=/var/lib/tftpboot
      --dhcp-match=set:bios,option:client-arch,0
      --dhcp-boot=tag:bios,undionly.kpxe
      --dhcp-match=set:efi32,option:client-arch,6
      --dhcp-boot=tag:efi32,ipxe.efi
      --dhcp-match=set:efibc,option:client-arch,7
      --dhcp-boot=tag:efibc,ipxe.efi
      --dhcp-match=set:efi64,option:client-arch,9
      --dhcp-boot=tag:efi64,ipxe.efi
      --dhcp-userclass=set:ipxe,iPXE
      --dhcp-boot=tag:ipxe,http://matchbox.home.box:8080/boot.ipxe
      --dhcp-option=option:netmask,255.255.0.0
      --address=/matchbox.home.box/10.179.1.2
      --address=/router.home.box/10.179.1.1
      --log-queries
      --log-dhcp
  matchbox:
    image:  quay.io/poseidon/matchbox:v0.10.0
    network_mode: "host"
    volumes:
      - /var/lib/matchbox:/var/lib/matchbox:Z
      - /etc/matchbox:/etc/matchbox:Z,ro
    command: >
      -address=0.0.0.0:8080 
      -rpc-address=0.0.0.0:8081
      -log-level=debug
