version: "3.9"
services:
  dnsmasq:
    image: quay.io/poseidon/dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: >
      -d -q
      --dhcp-range=10.179.2.1,10.179.3.254,255.255.254.0
      --dhcp-range=10.179.1.1,static,255.255.255.0,4h
      --dhcp-host=A0:63:91:E7:C0:88,router,10.179.1.1,4h
      --enable-tftp --tftp-root=/var/lib/tftpboot
      --dhcp-match=set:bios,option:client-arch,0
      --dhcp-boot=tag:bios,undionly.kpxe
      --dhcp-match=set:efi32,option:client-arch,6
      --dhcp-boot=tag:efi32,ipxe.efi
      --dhcp-match=set:efibc,option:client-arch,7
      --dhcp-boot=tag:efibc,ipxe.efi
      --dhcp-match=set:efi64,option:client-arch,9
      --dhcp-boot=tag:efi64,ipxe.efi
      --dhcp-userclass=set:ipxe,iPXE
      --dhcp-boot=tag:ipxe,http://matchbox.home.box:8080/boot.ipxe
      --address=/matchbox.home.box/10.179.1.2
      --address=/router.home.box/10.179.1.1
      --dhcp-option=option:router,10.179.1.1
      --dhcp-option=option:dns-server,1.1.1.1
      --server=1.1.1.1
      --server=8.8.8.8
      --log-queries
      --log-dhcp
  matchbox:
    image:  quay.io/poseidon/matchbox:v0.10.0
    network_mode: "host"
    volumes:
      - /var/lib/matchbox:/var/lib/matchbox:Z
      - /etc/matchbox:/etc/matchbox:Z,ro
    command: >
      -address=0.0.0.0:8080 
      -rpc-address=0.0.0.0:8081
      -log-level=debug
