version: "3.9"
services:
  dnsmasq:
    image: quay.io/poseidon/dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:Z
    command: -d 
  matchbox:
    image:  quay.io/poseidon/matchbox:v0.10.0
    network_mode: "host"
    volumes:
      - /var/lib/matchbox:/var/lib/matchbox:Z
      - /etc/matchbox:/etc/matchbox:Z,ro
    command: >
      -address=0.0.0.0:8080 
      -rpc-address=0.0.0.0:8081
      -log-level=debug
